name: CI Build with Qt 5.15

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest  # or windows-latest, macos-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Python (required for aqtinstall)
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Install aqtinstall (for Qt installation)
    - name: Install aqtinstall
      run: pip install aqtinstall

    # Install Qt 5.15 (replace "gcc_64" with the desired platform, such as "win64_msvc2019_64")
    - name: Install Qt 5.15
      run: |
        aqt install-qt linux desktop 5.15.2 gcc_64 --outputdir $HOME/Qt
        aqt install-qt linux desktop 5.15.2 gcc_64 --modules charts

    # Set up Qt environment variables
    - name: Set Qt environment variables
      run: |
        echo "QT_DIR=$HOME/Qt/5.15.2/gcc_64" >> $GITHUB_ENV
        echo "$QT_DIR/bin" >> $GITHUB_PATH

    # Install OpenGL dependencies
    - name: Install OpenGL dependencies
      run: sudo apt-get install -y mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev

    # Install necessary build tools (e.g., CMake or qmake)
    - name: Install build tools
      run: sudo apt-get install -y build-essential cmake

    # List Qt5 prefix path
    - name: List Qt files
      run: |
        ls $QT_DIR/lib/cmake/Qt5

    # Install necessary build tools (e.g., CMake or qmake)
    - name: Install build tools
      run: sudo apt-get install -y build-essential cmake

    # Build your project
    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_PREFIX_PATH=$QT_DIR/lib/cmake/Qt5
        cmake --build .

    # (Optional) Run tests if any
    - name: Run tests
      run: |
        cd build
        ctest
